apiVersion: apps/v1
kind: Deployment
metadata:
  name: bam-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bam-ui
  template:
    metadata:
      labels:
        app: bam-ui
    spec:
      containers:
        - name: bam-ui
          image: localhost:32000/bam-ui:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: bam-ui
spec:
  type: LoadBalancer
  selector:
    app: bam-ui
  ports:
    - port: 3000       
      targetPort: 80   
      protocol: TCP