apiVersion: apps/v1
kind: Deployment
metadata:
  name: bam-building
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: bam-building
  template:
    metadata:
      labels:
        app: bam-building
    spec:
      containers:
        - name: bam-building
          image: localhost:32000/bam-building:1.0
          startupProbe:
            httpGet:
              path: /healthz
              port: 8080
            periodSeconds: 30
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bam-building
spec:
  selector:
    app: bam-building
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP